components:
  schemas:
    Application_v1_0_1_Actions:
      additionalProperties: false
      description: The available actions for this resource.
      properties:
        '#Application.Reset':
          $ref: '#/components/schemas/Application_v1_0_1_Reset'
        Oem:
          $ref: '#/components/schemas/Application_v1_0_1_OemActions'
          description: The available OEM-specific actions for this resource.
          x-longDescription: This property shall contain the available OEM-specific
            actions for this resource.
      type: object
      x-longDescription: This type shall contain the available actions for this resource.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
    Application_v1_0_1_Application:
      additionalProperties: false
      description: The `Application` schema represents an application or service running
        on a computer system.
      properties:
        '@odata.context':
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_context
        '@odata.etag':
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_etag
        '@odata.id':
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_id
        '@odata.type':
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_type
        Actions:
          $ref: '#/components/schemas/Application_v1_0_1_Actions'
          description: The available actions for this resource.
          x-longDescription: This property shall contain the available actions for
            this resource.
        Description:
          oneOf:
          - $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Description
          - enum:
            - null
          readOnly: true
        DestinationURIs:
          description: The URIs to which this application pushes data.
          format: uri-reference
          items:
            nullable: true
            type: string
          readOnly: true
          type: array
          x-longDescription: This property shall contain an array of URIs to which
            this application pushes data.  This is typically for applications that
            act as logging or metric agents that transmit data captured to remote
            servers.
        Id:
          $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Id
          readOnly: true
        Links:
          $ref: '#/components/schemas/Application_v1_0_1_Links'
          description: The links to other resources that are related to this resource.
          x-longDescription: This property shall contain links to resources that are
            related to but are not contained by, or subordinate to, this resource.
        MetricsURIs:
          description: The URIs that provide access to data or other information in
            this application.
          format: uri-reference
          items:
            nullable: true
            type: string
          readOnly: true
          type: array
          x-longDescription: This property shall contain an array of URIs that provide
            access to data or other information in this application.  This is typically
            for applications that allow external users to perform requests to pull
            data from the application.
        Name:
          $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Name
          readOnly: true
        Oem:
          $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Oem
          description: The OEM extension property.
          x-longDescription: This property shall contain the OEM extensions.  All
            values for properties that this object contains shall conform to the Redfish
            Specification-described requirements.
        StartTime:
          description: The date and time when the application started running.
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall indicate the date and time when the
            application started running.
        Status:
          $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Status
          description: The status and health of the resource and its subordinate or
            dependent resources.
          x-longDescription: This property shall contain any status or health properties
            of the resource.
        Vendor:
          description: The vendor of this application.
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall contain the name of the company that
            provides this application.
        Version:
          description: The version of this application.
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall contain the version of this application.
      required:
      - '@odata.id'
      - '@odata.type'
      - Id
      - Name
      type: object
      x-longDescription: This resource shall represent an application or service running
        on a computer system.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
    Application_v1_0_1_Links:
      additionalProperties: false
      description: The links to other resources that are related to this resource.
      properties:
        Oem:
          $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Oem
          description: The OEM extension property.
          x-longDescription: This property shall contain the OEM extensions.  All
            values for properties contained in this object shall conform to the Redfish
            Specification-described requirements.
        SoftwareImage:
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_idRef
          description: The link to the software image for this application.
          readOnly: true
          x-longDescription: This property shall contain a link to a resource of type
            `SoftwareInventory` that represents the software image from which this
            application runs.
      type: object
      x-longDescription: This Redfish Specification-described type shall contain links
        to resources that are related to but are not contained by, or subordinate
        to, this resource.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
    Application_v1_0_1_OemActions:
      additionalProperties: true
      description: The available OEM-specific actions for this resource.
      properties: {}
      type: object
      x-longDescription: This type shall contain the available OEM-specific actions
        for this resource.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
    Application_v1_0_1_Reset:
      additionalProperties: false
      description: This action resets the application.
      properties:
        target:
          description: Link to invoke action
          format: uri-reference
          type: string
        title:
          description: Friendly action name
          type: string
      type: object
      x-longDescription: This action shall reset the application.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
    Application_v1_0_1_ResetRequestBody:
      additionalProperties: false
      description: This action resets the application.
      properties:
        ResetType:
          $ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_ResetType
          description: The type of reset.
          x-longDescription: This parameter shall contain the type of reset.  `GracefulRestart`
            and `ForceRestart` shall indicate requests to restart the application.  `GracefulShutdown`
            and `ForceOff` shall indicate requests to stop or disable the application.  `On`
            and `ForceOn` shall indicate requests to start or enable the application.  The
            service can accept a request without the parameter and shall perform a
            `GracefulRestart`.
      type: object
      x-longDescription: This action shall reset the application.
title: '#Application.v1_0_1.Application'
x-copyright: Copyright 2014-2024 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-language: en
x-owningEntity: DMTF
x-release: '2023.2'
