components:
  schemas:
    Settings:
      additionalProperties: false
      properties:
        ETag:
          description: The ETag of the resource to which the settings were applied,
            after the application.
          nullable: true
          readOnly: true
          type: string
          x-longDescription: The value of this property shall be the ETag of the resource
            to which the settings were applied, after the application.  This is here
            so that the client can check it against the ETag of the current resource
            to see if any other changes have also happened to the resource.
        Messages:
          description: This is an array of messages associated with the task.
          items:
            $ref: http://redfish.dmtf.org/schemas/v1/odata.v4_0_3.yaml#/components/schemas/idRef
          readOnly: true
          type: array
          x-longDescription: The value of this property shall be an array of messages
            associated with the task.
        SettingsObject:
          $ref: http://redfish.dmtf.org/schemas/v1/odata.4.0.0.yaml#/components/schemas/idRef
          description: Reference to the resource the client may PUT/PATCH to in order
            to change this resource.
          x-longDescription: The value of this property shall be the URI of the resource
            to which a client must do a PUT or PATCh in order to modify this resource.
        Time:
          description: Indicates the time the settings were applied.
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-longDescription: The value of this property shall indicate the time that
            the settings object was applied to the resource.
      type: object
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message|Privileges)\.[a-zA-Z_][a-zA-Z0-9_.]+$:
          description: This property shall specify a valid odata or Redfish property.
title: '#Settings.v1_0_2'
x-copyright: Copyright 2014-2016 Distributed Management Task Force, Inc. (DMTF). For
  the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
