components:
  schemas:
    ApplyTime:
      enum:
      - Immediate
      - OnReset
      - AtMaintenanceWindowStart
      - InMaintenanceWindowOnReset
      type: string
      x-enumDescriptions:
        AtMaintenanceWindowStart: Apply during a maintenance window as specified by
          an administrator.
        Immediate: Apply immediately.
        InMaintenanceWindowOnReset: Apply after a reset but within maintenance window
          as specified by an adminstrator.
        OnReset: Apply on a reset.
      x-enumLongDescriptions:
        AtMaintenanceWindowStart: This value shall indicate the values within the
          Settings Resource are applied during the maintenance window specified by
          the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds properties.  A
          service may perform resets during this maintenance window.
        Immediate: This value shall indicate the values within the Settings Resource
          are applied immediately.
        InMaintenanceWindowOnReset: This value shall indicate the values within the
          Settings Resource are applied during the maintenance window specified by
          the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds properties,
          and if a reset occurs within the maintenance window.
        OnReset: This value shall indicate the values within Settings Resource are
          applied when the system or service is reset.
    PreferredApplyTime:
      additionalProperties: false
      description: The preferred time to apply configuration settings.
      properties:
        ApplyTime:
          $ref: '#/components/schemas/ApplyTime'
          description: The time when to apply the settings.
          readOnly: false
          x-longDescription: This property shall indicate when to apply the values
            in this Settings Resource.
          x-versionAdded: v1_1_0
        MaintenanceWindowDurationInSeconds:
          description: The expiry time of maintenance window in seconds.
          minimum: 0
          readOnly: false
          type: integer
          x-longDescription: This property shall indicate the end of the maintenance
            window as the number of seconds after the time specified by the MaintenanceWindowStartTime
            property.  This property shall be required if the ApplyTime property is
            `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
          x-units: s
          x-versionAdded: v1_1_0
        MaintenanceWindowStartTime:
          description: The start time of a maintenance window.
          format: date-time
          readOnly: false
          type: string
          x-longDescription: This property shall indicate the date and time when the
            service can start to apply the future configuration as part of a maintenance
            window.  This property shall be required if the ApplyTime property is
            `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
          x-versionAdded: v1_1_0
      type: object
      x-longDescription: This type shall be specified by client to indicate the preferred
        time to apply the configuration settings.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
    Settings:
      additionalProperties: false
      description: The Resource settings.
      properties:
        ETag:
          description: The entity tag (ETag) of the Resource to which the settings
            were applied, after the application.
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall contain the entity tag (ETag) of
            the Resource to which the settings were applied, after the application.  The
            client can check this value against the ETag of this Resource to determine
            whether the Resource had other changes.
        Messages:
          description: An array of messages associated with the settings.
          items:
            $ref: http://redfish.dmtf.org/schemas/v1/Message.yaml#/components/schemas/Message
          type: array
          x-longDescription: This property shall contain an array of messages associated
            with the settings.
        SettingsObject:
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/idRef
          description: The link to the Resource that the client may PUT or PATCH to
            modify the Resource.
          readOnly: true
          x-longDescription: This property shall contain the URI of the Resource that
            the client may PUT or PATCH to modify the Resource.
        SupportedApplyTimes:
          description: The time when the settings can be applied.
          items:
            $ref: '#/components/schemas/ApplyTime'
          readOnly: true
          type: array
          x-longDescription: A service shall advertise its applytime capabilities
            by using this property to set the time when the settings can be applied.
          x-versionAdded: v1_1_0
        Time:
          description: The time when the settings were applied.
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall indicate the time when the settings
            were applied to the Resource.
      type: object
      x-longDescription: This type shall describe any settings of a Resource.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
title: '#Settings.v1_1_2'
x-copyright: Copyright 2014-2019 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
x-release: '2017.2'
