components:
  schemas:
    OperationApplyTime:
      enum:
      - Immediate
      - OnReset
      - AtMaintenanceWindowStart
      - InMaintenanceWindowOnReset
      type: string
      x-enumDescriptions:
        AtMaintenanceWindowStart: Apply the requested operation during a maintenance
          window as specified by an administrator.
        Immediate: Apply the requested operation immediately.
        InMaintenanceWindowOnReset: Apply the requested operation after a reset but
          within maintenance window as specified by an adminstrator.
        OnReset: Apply the requested operation on a reset.
      x-enumLongDescriptions:
        AtMaintenanceWindowStart: This OperationApplyTime value shall be used to indicate
          the requested Create, Delete, or Action operation is applied during the
          maintenance window specified by the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds
          properties.  A service may perform resets during this maintenance window.
        Immediate: This OperationApplyTime value shall be used to indicate the requested
          Create, Delete, or Action operation is applied immediately.
        InMaintenanceWindowOnReset: This OperationApplyTime value shall be used to
          indicate the requested Create, Delete, or Action operation is applied during
          the maintenance window specified by the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds
          properties, and if a reset occurs within the maintenance window.
        OnReset: This OperationApplyTime value shall be used to indicate the requested
          Create, Delete, or Action operation is applied when the system or service
          is reset.
    Settings:
      additionalProperties: false
      description: This type describes the settings of a resouce.
      properties:
        ETag:
          description: The ETag of the resource to which the settings were applied,
            after the application.
          nullable: true
          readOnly: true
          type: string
          x-longDescription: The value of this property shall be the ETag of the resource
            to which the settings were applied, after the application.  This is here
            so that the client can check it against the ETag of the current resource
            to see if any other changes have also happened to the resource.
        Messages:
          description: This is an array of messages associated with the task.
          items:
            $ref: http://redfish.dmtf.org/schemas/v1/odata.v4_0_3.yaml#/components/schemas/idRef
          type: array
          x-longDescription: The value of this property shall be an array of messages
            associated with the task.
        SettingsObject:
          $ref: http://redfish.dmtf.org/schemas/v1/odata.v4_0_3.yaml#/components/schemas/idRef
          description: Reference to the resource the client may PUT/PATCH to in order
            to change this resource.
          readOnly: true
          x-longDescription: The value of this property shall be the URI of the resource
            to which a client must do a PUT or PATCH in order to modify this resource.
        Time:
          description: Indicates the time the settings were applied.
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-longDescription: The value of this property shall indicate the time that
            the settings object was applied to the resource.
      type: object
      x-longDescription: This type shall describe any attributes of a resouce.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_.]+$:
          description: This property shall specify a valid odata or Redfish property.
title: '#Settings.v1_0_5'
x-copyright: Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
